# python abcrown.py --config exp_configs/my_configs/robustness_grey_base.yaml
model:
  name: Customized("my_models", "model_grey")
data:
  dataset: Customized("gtsrb_dataset", "gtsrb_32_grey")
  mean: [0.3211]
  std: [0.2230]
  num_outputs: 43
  start: 0
  end: 10 #215
attack:
  pgd_restarts: 100
solver:
  batch_size: 512
  beta-crown:
    iteration: 20
bab:
  timeout: 60