# python abcrown.py --config exp_configs/my_configs/robustness_grey_base.yaml
general:
  root_path: ../../dataset  # Root path of the csv file.
  csv_name: instances_eps_0.020.csv # Name of the csv file (ONLY one column listed paths to vnnlibs).
model:
  name: Customized("my_models", "superclass")
  input_shape: [-1, 1, 32, 32]
attack:
  pgd_restarts: 100
solver:
  batch_size: 64
  beta-crown:
    iteration: 20
bab:
  timeout: 150